/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dhpm11.tuan5.demotuan4;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;

/**
 *
 * @author Suong
 */
public class DemoBookSupplies extends javax.swing.JFrame {

    DefaultTableModel defaultTableModel = new DefaultTableModel();

    /**
     * Creates new form DemoBookSupplies
     */
    public DemoBookSupplies() throws SQLException {
        initComponents();
        initializeEditor();
        loadData();
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new Color(70, 3, 121));
        headerRenderer.setForeground(Color.WHITE);

        for (int i = 0; i < tblThongTin.getModel().getColumnCount(); i++) {
            tblThongTin.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }

        tblThongTin.setBackground(Color.GREEN);

        ImageIcon img = new ImageIcon("C:\\Users\\Suong\\Desktop\\hoctap\\nam3\\Java-Application\\Bai-Tap-Tuan\\src\\com\\dhpm11\\Tuan_4\\Home\\JavaApplication7\\src\\com\\dhpm11\\tuan4\\person-male.png");
        setIconImage(img.getImage());
    }

    private void initializeEditor() {
//        super.setDefaultEditor(boolean.class, super.getDefaultEditor(Boolean.class));
//        super.setDefaultEditor(int.class, super.getDefaultEditor(Integer.class));
//        super.setDefaultEditor(long.class, super.getDefaultEditor(Long.class));
//        super.setDefaultEditor(double.class, super.getDefaultEditor(Double.class));
//        super.setDefaultEditor(float.class, super.getDefaultEditor(Float.class));
//        super.setDefaultEditor(short.class, super.getDefaultEditor(Short.class));
//        super.setDefaultEditor(byte.class, super.getDefaultEditor(Byte.class));
//        super.setDefaultEditor(char.class, super.getDefaultEditor(Character.class));

        /* // Cho phep edit tren table
        * TableColumn clBooks = tblThongTin.getColumnModel().getColumn(2);
        * clBooks.setCellEditor(tblThongTin.getDefaultEditor(Boolean.class));
        * clBooks.setCellRenderer(tblThongTin.getDefaultRenderer(Boolean.class));
         */
        // Khong cho phep edit tren table
        tblThongTin.getColumnModel().getColumn(2).setCellRenderer(tblThongTin.getDefaultRenderer(Boolean.class));
        tblThongTin.getColumnModel().getColumn(3).setCellRenderer(tblThongTin.getDefaultRenderer(Boolean.class));
        tblThongTin.getColumnModel().getColumn(4).setCellRenderer(tblThongTin.getDefaultRenderer(Boolean.class));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnTop = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnBottom = new javax.swing.JPanel();
        scTable = new javax.swing.JScrollPane();
        tblThongTin = new javax.swing.JTable();
        pnCenter = new javax.swing.JPanel();
        pnNhapThongTin = new javax.swing.JPanel();
        lblSupplierID = new javax.swing.JLabel();
        txtSupplierID = new javax.swing.JTextField();
        lblSupplierIDError = new javax.swing.JLabel();
        lblSupplierName = new javax.swing.JLabel();
        txtSupplierName = new javax.swing.JTextField();
        lblSupplierNameError = new javax.swing.JLabel();
        lblSupplierType = new javax.swing.JLabel();
        ckbBooks = new javax.swing.JCheckBox();
        ckbNewsPapers = new javax.swing.JCheckBox();
        ckbJournalsandMagazines = new javax.swing.JCheckBox();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblAddressError = new javax.swing.JLabel();
        lblContactNo = new javax.swing.JLabel();
        txtContactNo = new javax.swing.JTextField();
        lblContactNoError = new javax.swing.JLabel();
        lblEmailID = new javax.swing.JLabel();
        txtEmailID = new javax.swing.JTextField();
        lblEmailIDError = new javax.swing.JLabel();
        lblRemarks = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRemarks = new javax.swing.JTextArea();
        pnThaoTac = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Demo Books Suppliers");

        pnMain.setLayout(new java.awt.BorderLayout());

        pnTop.setBackground(new java.awt.Color(0, 51, 51));
        pnTop.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Books Supplies");
        pnTop.add(jLabel1);

        pnMain.add(pnTop, java.awt.BorderLayout.PAGE_START);

        scTable.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        scTable.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblThongTin.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        tblThongTin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier ID", "Supplier Name", "Books", "News Papers", "Journals and Magazines", "Address", "Contact No", "Email ID", "Remarks"
            }
        ));
        tblThongTin.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThongTinMouseClicked(evt);
            }
        });
        tblThongTin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblThongTinKeyReleased(evt);
            }
        });
        scTable.setViewportView(tblThongTin);

        javax.swing.GroupLayout pnBottomLayout = new javax.swing.GroupLayout(pnBottom);
        pnBottom.setLayout(pnBottomLayout);
        pnBottomLayout.setHorizontalGroup(
            pnBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBottomLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(scTable, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );
        pnBottomLayout.setVerticalGroup(
            pnBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBottomLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(scTable, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnMain.add(pnBottom, java.awt.BorderLayout.PAGE_END);

        pnNhapThongTin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblSupplierID.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblSupplierID.setText("Supplier ID");

        lblSupplierIDError.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        lblSupplierIDError.setForeground(new java.awt.Color(255, 0, 0));

        lblSupplierName.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblSupplierName.setText("Supplier Name");

        lblSupplierNameError.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        lblSupplierNameError.setForeground(new java.awt.Color(255, 0, 0));

        lblSupplierType.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblSupplierType.setText("Supplier Type");

        ckbBooks.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ckbBooks.setText("Books");

        ckbNewsPapers.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ckbNewsPapers.setText("News Papers");

        ckbJournalsandMagazines.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ckbJournalsandMagazines.setText("Journals and Magazines");

        lblAddress.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblAddress.setText("Address");

        lblAddressError.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        lblAddressError.setForeground(new java.awt.Color(255, 0, 0));

        lblContactNo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblContactNo.setText("Contact No");

        lblContactNoError.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        lblContactNoError.setForeground(new java.awt.Color(255, 0, 0));

        lblEmailID.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblEmailID.setText("Email ID");

        lblEmailIDError.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        lblEmailIDError.setForeground(new java.awt.Color(255, 0, 0));

        lblRemarks.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblRemarks.setText("Remarks");

        txtRemarks.setColumns(20);
        txtRemarks.setRows(5);
        jScrollPane1.setViewportView(txtRemarks);

        javax.swing.GroupLayout pnNhapThongTinLayout = new javax.swing.GroupLayout(pnNhapThongTin);
        pnNhapThongTin.setLayout(pnNhapThongTinLayout);
        pnNhapThongTinLayout.setHorizontalGroup(
            pnNhapThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNhapThongTinLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnNhapThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnNhapThongTinLayout.createSequentialGroup()
                        .addGroup(pnNhapThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSupplierName)
                            .addComponent(lblSupplierID))
                        .addGap(39, 39, 39)
                        .addGroup(pnNhapThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnNhapThongTinLayout.createSequentialGroup()
                                .addComponent(txtSupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblSupplierIDError))
                            .addComponent(txtSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnNhapThongTinLayout.createSequentialGroup()
                                .addComponent(ckbBooks)
                                .addGap(18, 18, 18)
                                .addComponent(ckbNewsPapers)))
                        .addGroup(pnNhapThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnNhapThongTinLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(ckbJournalsandMagazines))
                            .addGroup(pnNhapThongTinLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(lblSupplierNameError))))
                    .addGroup(pnNhapThongTinLayout.createSequentialGroup()
                        .addGroup(pnNhapThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSupplierType)
                            .addComponent(lblAddress)
                            .addComponent(lblContactNo)
                            .addComponent(lblEmailID)
                            .addComponent(lblRemarks))
                        .addGap(44, 44, 44)
                        .addGroup(pnNhapThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddress)
                            .addComponent(jScrollPane1)
                            .addGroup(pnNhapThongTinLayout.createSequentialGroup()
                                .addGroup(pnNhapThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnNhapThongTinLayout.createSequentialGroup()
                                        .addComponent(txtEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblEmailIDError))
                                    .addGroup(pnNhapThongTinLayout.createSequentialGroup()
                                        .addComponent(txtContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblContactNoError)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addComponent(lblAddressError)
                .addContainerGap())
        );
        pnNhapThongTinLayout.setVerticalGroup(
            pnNhapThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNhapThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnNhapThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplierID)
                    .addComponent(txtSupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSupplierIDError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnNhapThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplierName)
                    .addComponent(txtSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSupplierNameError))
                .addGap(11, 11, 11)
                .addGroup(pnNhapThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplierType)
                    .addComponent(ckbBooks)
                    .addComponent(ckbNewsPapers)
                    .addComponent(ckbJournalsandMagazines))
                .addGap(11, 11, 11)
                .addGroup(pnNhapThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddressError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnNhapThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContactNo)
                    .addComponent(txtContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContactNoError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnNhapThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailID)
                    .addComponent(txtEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailIDError))
                .addGap(11, 11, 11)
                .addGroup(pnNhapThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnNhapThongTinLayout.createSequentialGroup()
                        .addComponent(lblRemarks)
                        .addGap(89, 89, 89))
                    .addGroup(pnNhapThongTinLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pnThaoTac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnNew.setBackground(new java.awt.Color(0, 51, 0));
        btnNew.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnNew.setForeground(new java.awt.Color(255, 255, 255));
        btnNew.setMnemonic('N');
        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        pnThaoTac.add(btnNew);

        btnSave.setBackground(new java.awt.Color(255, 51, 0));
        btnSave.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setMnemonic('S');
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pnThaoTac.add(btnSave);

        btnDelete.setBackground(new java.awt.Color(0, 51, 51));
        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setMnemonic('D');
        btnDelete.setText("Delete");
        btnDelete.setToolTipText("");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        pnThaoTac.add(btnDelete);

        btnUpdate.setBackground(new java.awt.Color(153, 0, 0));
        btnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setMnemonic('U');
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        pnThaoTac.add(btnUpdate);

        javax.swing.GroupLayout pnCenterLayout = new javax.swing.GroupLayout(pnCenter);
        pnCenter.setLayout(pnCenterLayout);
        pnCenterLayout.setHorizontalGroup(
            pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCenterLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnNhapThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnThaoTac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );
        pnCenterLayout.setVerticalGroup(
            pnCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnNhapThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnThaoTac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        pnMain.add(pnCenter, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        removeTxt();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            String id = txtSupplierID.getText().trim();
            String remarks = txtRemarks.getText().trim();
            String email = txtEmailID.getText().trim();
            String contact = txtContactNo.getText().trim();
            String address = txtAddress.getText().trim();
            String name = txtSupplierName.getText().trim();
            if (id.isEmpty() || email.isEmpty() || contact.isEmpty() || address.isEmpty() || name.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin!");
                errors(txtSupplierID, lblSupplierIDError);
                errors(txtEmailID, lblEmailIDError);
                errors(txtContactNo, lblContactNoError);
                errors(txtAddress, lblAddressError);
                errors(txtSupplierName, lblSupplierNameError);
            } else {
                errors(txtSupplierID, lblSupplierIDError);
                errors(txtEmailID, lblEmailIDError);
                errors(txtContactNo, lblContactNoError);
                errors(txtAddress, lblAddressError);
                errors(txtSupplierName, lblSupplierNameError);
                if (QueryPrepareStatement.checkRecords(id) == false) {
                    int ret = JOptionPane.showConfirmDialog(null, "Lưu lại hả?", "Save", JOptionPane.YES_NO_OPTION);
                    if (ret == JOptionPane.YES_OPTION) {
                        try {
                            boolean books = false;
                            books = ckbBooks.isSelected();
                            boolean newspapers = false;
                            newspapers = ckbNewsPapers.isSelected();
                            boolean journalsandmagazines = false;
                            journalsandmagazines = ckbJournalsandMagazines.isSelected();
                            QueryPrepareStatement.insertRecords(id, name, books, newspapers, journalsandmagazines, address, contact, email, remarks);
                            JOptionPane.showMessageDialog(null, "Thêm thành công");
                            loadData();
                        } catch (SQLException ex) {
                            Logger.getLogger(DemoBookSupplies.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (NumberFormatException e) {
                            System.out.println("lỗi");
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Đã tồn tại, vui lòng nhập ID mới!");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(DemoBookSupplies.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            String id = txtSupplierID.getText().trim();
            String remarks = txtRemarks.getText().trim();
            String email = txtEmailID.getText().trim();
            String contact = txtContactNo.getText().trim();
            String address = txtAddress.getText().trim();
            String name = txtSupplierName.getText().trim();
            if (QueryPrepareStatement.checkRecords(id)) {
                int ret = JOptionPane.showConfirmDialog(null, "Cập nhật hả?", "Update", JOptionPane.YES_NO_OPTION);
                if (ret == JOptionPane.YES_OPTION) {
                    try {
                        boolean books = false;
                        books = ckbBooks.isSelected();
                        boolean newspapers = false;
                        newspapers = ckbNewsPapers.isSelected();
                        boolean journalsandmagazines = false;
                        journalsandmagazines = ckbJournalsandMagazines.isSelected();
                        QueryPrepareStatement.updateRecords(id, name, books, newspapers, journalsandmagazines, address, contact, email, remarks);
                        JOptionPane.showMessageDialog(null, "Cập nhật thành công");
                        loadData();
                    } catch (SQLException ex) {
                        Logger.getLogger(DemoBookSupplies.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (NumberFormatException e) {
                        System.out.println("lỗi");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Vui lòng kiểm tra lại ID! Không tìm thấy thông tin.");
            }
            lblSupplierIDError.setText("");
            lblSupplierNameError.setText("");
            lblEmailIDError.setText("");
            lblContactNoError.setText("");
            lblAddressError.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(DemoBookSupplies.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            String id = txtSupplierID.getText().trim();
            if (QueryPrepareStatement.checkRecords(id)) {
                int ret = JOptionPane.showConfirmDialog(null, "Xóa hả?", "Delete", JOptionPane.YES_NO_OPTION);
                if (ret == JOptionPane.YES_OPTION) {
                    try {
                        QueryPrepareStatement.deleteRecords(id);
                        JOptionPane.showMessageDialog(null, "Xóa thành công");
                        loadData();
                        removeTxt();
                    } catch (SQLException ex) {
                        Logger.getLogger(DemoBookSupplies.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Vui lòng kiểm tra lại ID! Không tìm thấy thông tin.");
            }
            lblSupplierIDError.setText("");
            lblSupplierNameError.setText("");
            lblEmailIDError.setText("");
            lblContactNoError.setText("");
            lblAddressError.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(DemoBookSupplies.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblThongTinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongTinMouseClicked
        int selectedRow = tblThongTin.getSelectedRow();

        displayDetails(selectedRow);

        if (evt.getClickCount() == 2) {
            int selectedCol = tblThongTin.getSelectedColumn();
            JOptionPane.showMessageDialog(null, defaultTableModel.getValueAt(selectedRow, selectedCol));
        }
    }//GEN-LAST:event_tblThongTinMouseClicked

    private void tblThongTinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblThongTinKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            int selectedRow = tblThongTin.getSelectedRow();
            displayDetails(selectedRow);
        }
    }//GEN-LAST:event_tblThongTinKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DemoBookSupplies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DemoBookSupplies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DemoBookSupplies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DemoBookSupplies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DemoBookSupplies().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(DemoBookSupplies.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox ckbBooks;
    private javax.swing.JCheckBox ckbJournalsandMagazines;
    private javax.swing.JCheckBox ckbNewsPapers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAddressError;
    private javax.swing.JLabel lblContactNo;
    private javax.swing.JLabel lblContactNoError;
    private javax.swing.JLabel lblEmailID;
    private javax.swing.JLabel lblEmailIDError;
    private javax.swing.JLabel lblRemarks;
    private javax.swing.JLabel lblSupplierID;
    private javax.swing.JLabel lblSupplierIDError;
    private javax.swing.JLabel lblSupplierName;
    private javax.swing.JLabel lblSupplierNameError;
    private javax.swing.JLabel lblSupplierType;
    private javax.swing.JPanel pnBottom;
    private javax.swing.JPanel pnCenter;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnNhapThongTin;
    private javax.swing.JPanel pnThaoTac;
    private javax.swing.JPanel pnTop;
    private javax.swing.JScrollPane scTable;
    private javax.swing.JTable tblThongTin;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtEmailID;
    private javax.swing.JTextArea txtRemarks;
    private javax.swing.JTextField txtSupplierID;
    private javax.swing.JTextField txtSupplierName;
    // End of variables declaration//GEN-END:variables

    private void loadData() throws SQLException {
        tblThongTin.setDefaultEditor(Object.class, null);
        defaultTableModel.setRowCount(0);
        List<ThongTin> infos = QueryPrepareStatement.getInfo();
        defaultTableModel = (DefaultTableModel) tblThongTin.getModel();
        Object rowData[] = new Object[7];
        for (ThongTin info : infos) {
            System.out.println(info.getId() + info.getName() + info.isBooks() + info.getAddress() + info.getContact() + info.getEmail() + info.getRemarks());
            defaultTableModel.addRow(new Object[]{info.getId(), info.getName(), info.isBooks(), info.isNewspapers(), info.isJournalsandmagazines(), info.getAddress(), info.getContact(), info.getEmail(), info.getRemarks()});
        }
    }

    private void displayDetails(int selectedRow) {
        String id = (String) defaultTableModel.getValueAt(selectedRow, 0);
        String name = (String) defaultTableModel.getValueAt(selectedRow, 1);
        boolean books = (boolean) defaultTableModel.getValueAt(selectedRow, 2);
        boolean newspapers = (boolean) defaultTableModel.getValueAt(selectedRow, 3);
        boolean journalsandmagazines = (boolean) defaultTableModel.getValueAt(selectedRow, 4);
        String address = (String) defaultTableModel.getValueAt(selectedRow, 5);
        String contactno = (String) defaultTableModel.getValueAt(selectedRow, 6);
        String emalid = (String) defaultTableModel.getValueAt(selectedRow, 7);
        String remarks = (String) defaultTableModel.getValueAt(selectedRow, 8);

        txtSupplierID.setText(String.valueOf(id));
        txtSupplierName.setText(name);
        ckbBooks.setSelected(books);
        ckbNewsPapers.setSelected(newspapers);
        ckbJournalsandMagazines.setSelected(journalsandmagazines);
        txtAddress.setText(address);
        txtContactNo.setText(contactno);
        txtEmailID.setText(emalid);
        txtRemarks.setText(remarks);
    }

    private void removeTxt() {
        txtSupplierID.setText("");
        txtSupplierName.setText("");
        ckbBooks.setSelected(false);
        ckbJournalsandMagazines.setSelected(false);
        ckbNewsPapers.setSelected(false);
        txtAddress.setText("");
        txtContactNo.setText("");
        txtEmailID.setText("");
        txtRemarks.setText("");
        txtSupplierID.requestFocus();
        tblThongTin.getSelectionModel().clearSelection();
        errors(txtSupplierID, lblSupplierIDError);
        errors(txtEmailID, lblEmailIDError);
        errors(txtContactNo, lblContactNoError);
        errors(txtAddress, lblAddressError);
        errors(txtSupplierName, lblSupplierNameError);
    }

    private void errors(JTextField textField, JLabel error) {
        if (textField.getText().trim().isEmpty()) {
            error.setText("Không được trống!");
        } else {
            error.setText("");
        }
    }
}
